name: lumberdashui
description: A lumberdash client wich shows the logs in a widget inside your app.
version: 0.1.1
homepage: https://uekoetter.dev
repository: https://github.com/ueman/lumberdash_ui
issue_tracker: https://github.com/ueman/lumberdash_ui/issues

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  lumberdash: ">=2.1.1 <3.0.0"
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter